## Paper: Efficiently solving the practical vehicle routing problem

Source: `Duan et al., ‘Efficiently Solving the Practical Vehicle Routing Problem’.`

In [280]:
import pickle
import math
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import DataLoader, Dataset
from pathlib import Path

In [281]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
print("Device", device)

Device cpu


In [282]:
INSTANCE_PATH = Path("data")
RESULTS_PATH = Path("results")

In [283]:
with open(INSTANCE_PATH / 'dataset.pkl', 'rb') as f:
    graphs = pickle.load(f)

In [284]:
graphs[0]

(array([[0.5       , 0.5       , 0.        ],
        [0.06505159, 0.94888554, 2.        ],
        [0.96563203, 0.80839735, 4.        ],
        [0.30461377, 0.09767211, 8.        ],
        [0.68423303, 0.44015249, 7.        ],
        [0.12203823, 0.49517691, 9.        ],
        [0.03438852, 0.9093204 , 8.        ],
        [0.25877998, 0.66252228, 5.        ],
        [0.31171108, 0.52006802, 2.        ],
        [0.54671028, 0.18485446, 5.        ],
        [0.96958463, 0.77513282, 8.        ]]),
 array([-1,  0,  1,  2,  1,  0,  0,  0,  2,  2,  1]))

In [285]:
def get_distance(pointA, pointB):
    # Efficient way to calculate the euclidean distance
    return np.linalg.norm(pointA - pointB)

In [286]:
def pre_process_graph(graph):
    nodes, label = graph
    
    label = torch.tensor(label + 1, dtype=torch.int64)
    graph = torch.tensor(nodes[:, :-1], dtype=torch.float32)
    demand = torch.tensor(nodes[:, -1], dtype=torch.float32)
    distance = np.zeros((nodes.shape[0], nodes.shape[0]))

    for i in range(len(distance)):
        for j in range(i + 1, len(distance)):
            d = get_distance(graph[i], graph[j])
            distance[i][j] = d
            distance[j][i] = d
            
    distance = torch.tensor(distance, dtype=torch.float32)
            
    return graph, demand, distance, label

In [287]:
class GraphDataset(Dataset):
    def __init__(self, data):
        super().__init__()
        self.graphs = []
        self.demands = []
        self.distances = []
        self.labels = []
        
        for i in range(len(data)):
            processed = pre_process_graph(data[i])
            
            self.graphs.append(processed[0])
            self.demands.append(processed[1])
            self.distances.append(processed[2])
            self.labels.append(processed[3])

    def __len__(self):
        return len(self.graphs)

    def __getitem__(self, idx):
        graph = self.graphs[idx]
        demand = self.demands[idx]
        distance = self.distances[idx]
        label = self.labels[idx]
        
        return graph, demand, distance, label
    
    def __repr__(self):
        return f"GraphDataset(graphs={len(self.graphs)})"

The dataset should still be split in a train and test dataset

In [348]:
cut_off = int(len(graphs) * 0.9)

graph_train_dataset = GraphDataset(graphs[:cut_off])
graph_test_dataset = GraphDataset(graphs[cut_off:])

graph_train_dataset, graph_test_dataset

(GraphDataset(graphs=1800), GraphDataset(graphs=200))

In [349]:
train_dataloader = DataLoader(graph_train_dataset, batch_size=64, shuffle=True)
test_dataloader = DataLoader(graph_test_dataset, batch_size=64, shuffle=True)

## Attention Encoder

In [350]:
class AttentionEncoder(nn.Module):
    def __init__(self, hidden_dim):
        super(AttentionEncoder, self).__init__()
        self.hidden_dim = hidden_dim

    def forward(self, x, neighbor):
        '''
        @param x: (batch_size, node_num, hidden_dim)
        @param neighbor: (batch_size, node_num, k, hidden_dim)
        '''
        # scaled dot-product attention
        x = x.unsqueeze(2)
        neighbor = neighbor.permute(0, 1, 3, 2)
        attn_score = F.softmax(torch.matmul(x, neighbor) / np.sqrt(self.hidden_dim), dim=-1) # (batch_size, node_num, 1, k)
        weighted_neighbor = attn_score * neighbor
        
        # aggregation
        agg = x.squeeze(2) + torch.sum(weighted_neighbor, dim=-1)
        
        return agg

class AttentionPointer(nn.Module):
    def __init__(self, hidden_dim, use_tanh=False, use_cuda=False):
        super(AttentionPointer, self).__init__()
        self.hidden_dim = hidden_dim
        self.use_tanh = use_tanh

        self.project_hidden = nn.Linear(hidden_dim, hidden_dim)
        self.project_x = nn.Conv1d(hidden_dim, hidden_dim, 1, 1)
        self.C = 10
        self.tanh = nn.Tanh()

        v = torch.FloatTensor(hidden_dim)
        if use_cuda:
            v = v.cuda()
        self.v = nn.Parameter(v)
        self.v.data.uniform_(-(1. / math.sqrt(hidden_dim)) , 1. / math.sqrt(hidden_dim))

    def forward(self, hidden, x):
        '''
        @param hidden: (batch_size, hidden_dim)
        @param x: (node_num, batch_size, hidden_dim)
        '''
        x = x.permute(1, 2, 0)
        q = self.project_hidden(hidden).unsqueeze(2)  # batch_size x hidden_dim x 1
        e = self.project_x(x)  # batch_size x hidden_dim x node_num 
        # expand the hidden by node_num
        # batch_size x hidden_dim x node_num
        expanded_q = q.repeat(1, 1, e.size(2)) 
        # batch x 1 x hidden_dim
        v_view = self.v.unsqueeze(0).expand(expanded_q.size(0), len(self.v)).unsqueeze(1)
        # (batch_size x 1 x hidden_dim) * (batch_size x hidden_dim x node_num)
        u = torch.bmm(v_view, self.tanh(expanded_q + e)).squeeze(1)
        if self.use_tanh:
            logits = self.C * self.tanh(u)
        else:
            logits = u  
        return e, logits

## GCN

In [351]:
class GCN(nn.Module):
    def __init__(self,
                 node_hidden_dim,
                 edge_hidden_dim,
                 gcn_num_layers,
                 k):
        super(GCN, self).__init__()

        self.node_hidden_dim = node_hidden_dim
        self.edge_hidden_dim = edge_hidden_dim
        self.gcn_num_layers = gcn_num_layers
        self.k = k
        
        self.W1 = nn.Linear(2, self.node_hidden_dim)      # node_W1
        self.W2 = nn.Linear(2, self.node_hidden_dim // 2) # node_W2
        self.W3 = nn.Linear(1, self.node_hidden_dim // 2) # node_W3
        self.W4 = nn.Linear(1, self.edge_hidden_dim // 2) # edge_W4
        self.W5 = nn.Linear(1, self.edge_hidden_dim // 2) # edge_W5
        
        self.node_embedding = nn.Linear(self.node_hidden_dim, self.node_hidden_dim, bias=False) # Eq5
        self.edge_embedding = nn.Linear(self.edge_hidden_dim, self.edge_hidden_dim, bias=False) # Eq6

        self.gcn_layers = nn.ModuleList([GCNLayer(self.node_hidden_dim) for i in range(self.gcn_num_layers)])
        
        # Concat of the data (OWN)
        num_nodes = 11
        num_classes = 5
        
        self.final = nn.Linear(node_hidden_dim * num_nodes + edge_hidden_dim * num_nodes ** 2, num_nodes * num_classes)
        
        self.relu = nn.ReLU()

    def adjacency(self, m):
        '''
        @param m: distance (node_num, node_num)
        '''
        a = torch.zeros_like(m)
        idx = torch.argsort(m, dim=1)[:, 1:(self.k+1)]
        a.scatter_(1, idx, 1)
        a.fill_diagonal_(-1)

        return a

    def find_neighbors(self, m):
        ''' find index of neighbors for each node
        @param m: distance (batch_size, node_num, node_num)
        '''
        neighbor_idx = []
        for i in range(m.shape[0]):
            idx = torch.argsort(m[i, :, :], dim=1)[:, 1:(self.k+1)].numpy()
            neighbor_idx.append(idx)
        return torch.LongTensor(neighbor_idx).to(device)

    def forward(self, x_c, x_d, m):
        '''
        @param x_c: coordination (batch_size, node_num(N+1), 2)
        @param x_d: demand (batch_size, node_num(N+1))
        @param m: distance (batch_size, node_num(N+1), node_num(N+1))
        '''
        # Eq 2
        x0 = self.relu(self.W1(x_c[:, :1, :])) # (batch_size, 1, node_hidden_dim)
        xi = self.relu(torch.cat((self.W2(x_c[:, 1:, :]), self.W3(x_d.unsqueeze(2)[:, 1:, :])), dim=-1)) # (batch_size, node_num(N), node_hidden_dim)
        x = torch.cat((x0, xi), dim=1)
        # Eq 3
        a = torch.Tensor([self.adjacency(m[i, :, :]).numpy() for i in range(m.shape[0])]).to(device)
        # Eq 4
        y = self.relu(torch.cat((self.W4(m.unsqueeze(3)), self.W5(a.unsqueeze(3))), dim=-1))
        # Eq 5
        h_node = self.node_embedding(x)
        # Eq 6
        h_edge = self.edge_embedding(y)

        # index of neighbors
        N = self.find_neighbors(m)

        # GCN layers
        for gcn_layer in self.gcn_layers:
            h_node, h_edge = gcn_layer(h_node, h_edge, N)
            
        # Merge together (OWN)
        batch_size = h_node.size(0)
        h = torch.cat((h_node.reshape(batch_size, -1), h_edge.reshape(batch_size, -1)), dim=1)
        
        f = self.final(h)
#         return h_node, h_edge
        return f


class GCNLayer(nn.Module):
    def __init__(self, hidden_dim):
        super(GCNLayer, self).__init__()

        # node GCN layers
        self.W_node = nn.Linear(hidden_dim, hidden_dim)
        self.V_node_in = nn.Linear(hidden_dim, hidden_dim)
        self.V_node = nn.Linear(2 * hidden_dim, hidden_dim)
        self.attn = AttentionEncoder(hidden_dim)
        self.relu = nn.ReLU()
        self.ln1_node = nn.LayerNorm(hidden_dim)
        self.ln2_node = nn.LayerNorm(hidden_dim)

        # edge GCN layers
        self.W_edge = nn.Linear(hidden_dim, hidden_dim)
        self.V_edge_in = nn.Linear(hidden_dim, hidden_dim)
        self.V_edge = nn.Linear(2 * hidden_dim, hidden_dim)
        self.W1_edge = nn.Linear(hidden_dim, hidden_dim)
        self.W2_edge = nn.Linear(hidden_dim, hidden_dim)
        self.W3_edge = nn.Linear(hidden_dim, hidden_dim)
        self.relu = nn.ReLU()
        self.ln1_edge = nn.LayerNorm(hidden_dim)
        self.ln2_edge = nn.LayerNorm(hidden_dim)

        self.hidden_dim = hidden_dim

    def forward(self, x, e, neighbor_index):
        '''
        @param x: (batch_size, node_num(N+1), node_hidden_dim)
        @param e: (batch_size, node_num(N+1), node_num(N+1), edge_hidden_dim)
        @param neighbor_index: (batch_size, node_num(N+1), k)
        '''
        # node embedding
        batch_size, node_num = x.size(0), x.size(1)
        node_hidden_dim = x.size(-1)
        t = x.unsqueeze(1).repeat(1, node_num, 1, 1)

        neighbor_index = neighbor_index.unsqueeze(3).repeat(1, 1, 1, node_hidden_dim)
        neighbor = t.gather(2, neighbor_index)
        neighbor = neighbor.view(batch_size, node_num, -1, node_hidden_dim)
        
        # Eq 7/9
        h_nb_node = self.ln1_node(x + self.relu(self.W_node(self.attn(x, neighbor))))
        # Eq 12, Eq 8
        h_node = self.ln2_node(h_nb_node + self.relu(self.V_node(torch.cat([self.V_node_in(x), h_nb_node], dim=-1))))

        # edge embedding
        x_from = x.unsqueeze(2).repeat(1, 1, node_num, 1)
        x_to = x.unsqueeze(1).repeat(1, node_num, 1, 1)
        # Eq 7/10, Eq 11
        h_nb_edge = self.ln1_edge(e + self.relu(self.W_edge(self.W1_edge(e) + self.W2_edge(x_from) + self.W3_edge(x_to))))
        # Eq 13, Eq 8
        h_edge = self.ln2_edge(h_nb_edge + self.relu(self.V_edge(torch.cat((self.V_edge_in(e), h_nb_edge), dim=-1))))

        return h_node, h_edge

In [352]:
NODE_HIDDEN = 2
EDGE_HIDDEN = 2
GCN_LAYER = 2
k = 1

learning_rate = 1e-4
weight_decay = 0.96

model = GCN(node_hidden_dim=NODE_HIDDEN,
            edge_hidden_dim=EDGE_HIDDEN,
            gcn_num_layers=GCN_LAYER,
            k=k).to(device)

optimizer = torch.optim.Adam(model.parameters(),
                             lr=learning_rate,
                             weight_decay=weight_decay)
criterion = nn.CrossEntropyLoss()

In [357]:
def accuracy(out, labels):
    out = out.numpy()
    labels = labels.numpy()
    
    acc = np.sum(out == labels, axis=1) / out.shape[1]
    
    return np.mean(acc)

In [358]:
def test(x_c, x_d, m, y):
    model.eval()

    with torch.no_grad():
        out = model(x_c, x_d, m)
        out = out.reshape(out.size(0), 5, -1)
        out = out.softmax(1)
        out = out.argmax(1)

        return accuracy(out, y), out

In [359]:
def train_one_epoch(x_c, x_d, m, y):
    model.train()
    
    optimizer.zero_grad()
    
    out = model(x_c, x_d, m)
    out = out.reshape(out.size(0), 5, -1)
    
    loss = criterion(out, y)
    loss.backward()
    
    optimizer.step()

    return loss

In [360]:
def train(num_epochs):
    for epoch in range(num_epochs):
        epoch_loss = 0
    
        for x_c, x_d, m, y in train_dataloader:
            x_c, x_d, m, y = x_c.to(device), x_d.to(device), m.to(device), y.to(device)

            loss = train_one_epoch(x_c, x_d, m, y)
            epoch_loss += loss.item()

        print(f'Epoch: {epoch:02d}, Loss: {loss:.4f}')

In [356]:
train(50)

Epoch: 00, Loss: 1.5517
Epoch: 01, Loss: 1.5084
Epoch: 02, Loss: 1.4073
Epoch: 03, Loss: 1.3666
Epoch: 04, Loss: 1.3287
Epoch: 05, Loss: 1.2670
Epoch: 06, Loss: 1.3302
Epoch: 07, Loss: 1.3111
Epoch: 08, Loss: 1.2942
Epoch: 09, Loss: 1.3153
Epoch: 10, Loss: 1.2277
Epoch: 11, Loss: 1.1901
Epoch: 12, Loss: 1.3378
Epoch: 13, Loss: 1.2756
Epoch: 14, Loss: 1.2316
Epoch: 15, Loss: 1.2670
Epoch: 16, Loss: 1.3305
Epoch: 17, Loss: 1.2406
Epoch: 18, Loss: 1.3305
Epoch: 19, Loss: 1.3180
Epoch: 20, Loss: 1.2653
Epoch: 21, Loss: 1.1840
Epoch: 22, Loss: 1.1894
Epoch: 23, Loss: 1.1039
Epoch: 24, Loss: 1.1247
Epoch: 25, Loss: 1.1216
Epoch: 26, Loss: 1.0895
Epoch: 27, Loss: 1.0272
Epoch: 28, Loss: 0.9986
Epoch: 29, Loss: 1.3137
Epoch: 30, Loss: 1.1698
Epoch: 31, Loss: 1.1401
Epoch: 32, Loss: 1.1622
Epoch: 33, Loss: 1.1107
Epoch: 34, Loss: 1.2913
Epoch: 35, Loss: 1.0609
Epoch: 36, Loss: 1.0638
Epoch: 37, Loss: 1.1781
Epoch: 38, Loss: 1.1915
Epoch: 39, Loss: 1.1096
Epoch: 40, Loss: 1.0930
Epoch: 41, Loss:

In [361]:
x_c, x_d, m, y = next(iter(test_dataloader))

In [362]:
test(x_c, x_d, m, y)

(0.42471590909090906,
 tensor([[0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1],
         [